### ISSUE TITLE
关于复现代码

### ISSUE THREAD

**Issue by yiphingzhang** [AtmaHou/PromptSlotTagging#3]
您好，我复现了snips的其中2个领域，都是得到五十几分，有点低，不知道是哪里错了，还是没有这边公布可以复现到最高分的部分代码？

**Comment by left111** [comment]
感谢您指出问题，snips是跨领域的训练的setting，需要现在源域上进行训练然后在load模型进行测试，我们给出的脚本中忘记了加上--do_train和--do_dev，我们会在第一时间进行修改
