### ISSUE TITLE
关于代码复现

### ISSUE THREAD

**Issue by hccngu** [AtmaHou/PromptSlotTagging#4]
感谢您开源您的代码，我在复现snips数据集上的实验时，发现最终F1值只有58左右，我查看了之前的issue，我检查了配置文件中--do_train及--do_dev都已加上，结果仍为58左右，请问是发布的超参数设置或者其他什么问题吗？非常感谢～

**Comment by left111** [comment]
再次抱歉，论文中的报告的snips结果是5shot的，我们忘记release 5shot snips的实验数据了，我们已经上传，并修改了readme相关部分、snips脚本以匹配5shot数据等
