### ISSUE TITLE
同类型多实体

### ISSUE THREAD

**Issue by YuxiangLee1224** [AtmaHou/PromptSlotTagging#6]
您好！我想问下论文中的模型可以处理一句话里存在的同类型的多实体吗？比如一句话里面出现两个人名： 苏格拉底是柏拉图的老师。它可以把人名都识别出来吗？

**Comment by left111** [comment]
您好，论文中的模型可以处理一句话里存在的同类型的多实体的。我们采用了<；>作为分隔符用来分隔同类别的不同实体；在训练时计算<实体1><;><实体2>上的损失，以便模型能学习到处理类别的不同实体能力；在测试时我们将<;>添加到生成词表中，模型当遇到同类别的不同实体时模型就期望会生成<;>来分隔多个同类别实体。如“苏格拉底是柏拉图的老师。”人名指的是苏格拉底；柏拉图。

**Comment by YuxiangLee1224** [comment]
好的，十分感谢！
