### ISSUE TITLE
限制LM生成

### ISSUE THREAD

**Issue by YuxiangLee1224** [AtmaHou/PromptSlotTagging#7]
您好！再次打扰一下，想问下在论文中提到的在生成过程中，限制 LM 只生成出现在原始输入句子或预定义控制词中的词。这个是怎么做的？

**Comment by left111** [comment]
我们构造数据时有一个original_seq_in字段保留了原始句子中的词，在dataloader中又添加了预定义控制词https://github.com/AtmaHou/PromptSlotTagging/blob/5926b0fe12c8c9e8c075739a9b1bd898d77f4ad2/dataloader.py#L218-L221
之后作为encoded_raw_sent一起由dataloader返回，在https://github.com/AtmaHou/PromptSlotTagging/blob/5926b0fe12c8c9e8c075739a9b1bd898d77f4ad2/train.py#L44-L47
中我们只取encoded_raw_sent中的logits再进行处理。

注：我们的代码中只简单实现了限制 LM 只生成出现在原始输入句子或预定义控制词中的词，并且取得logits进行计算，并不能根据已生成词进行控制。
最新的huggingface的generate方法中有根据已生成内容限制词表的参数可以选择使用https://huggingface.co/docs/transformers/v4.28.1/en/main_classes/text_generation#transformers.GenerationMixin.generate.prefix_allowed_tokens_fn
